# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Copy
      run: |
        mkdir -p ../works/Projections_of_impressions
        cp -r ./* ../works/Projections_of_impressions/
        mv ../works ./

    - uses: iksaku/openstack-swift-action@master
      env:
        OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
        OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
        OS_USERNAME: ${{ secrets.OS_USERNAME }}
        OS_TENANT_NAME: ${{ secrets.OS_TENANT_NAME }}
      with:
        args: upload iiiex ./works/Projections_of_impressions/*
